services:
  - type: web
    name: ollama-llama3
    env: docker
    repo: https://github.com/Boomikaads/Render-Ollama.git
    branch: main
    plan: starter
    dockerfilePath: ./Dockerfile
    disk:
      name: ollama-data
      mountPath: /root/.ollama
      sizeGB: 50
    envVars:
      - key: PORT
        value: "11434"
    healthCheckPath: /

